config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :articles, shallow: true
  end
  get "/search", to: "blogs#show"
  get "welcome/index"
  root to: "welcome#index"
  # get "/user_blog", to: "user_blogs#change_role"
  post "/user_blog", to: "user_blogs#change_role"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :blog
  enum publish: { yes: 0, no: 1 }
  scope :published, -> { where(publish: 'yes') }
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true

  has_many :articles, dependent: :delete_all
  has_many :user_blogs, dependent: :delete_all
  has_many :users, through: :user_blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_blogs, dependent: :delete_all
  has_many :blogs, through: :user_blogs
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_blog.rb
class UserBlog < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  enum role: { viewer: 0, owner: 1, editor: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[edit update show destroy]
  before_action :find_blog, only: %i[index new create destroy]
  before_action :authenticate_user!

  def index
    if current_user.blog_ids.include?(params[:blog_id].to_i)
      @articles = Blog.find(params[:blog_id]).articles
    else
      @articles = Article.where(blog_id: params[:blog_id]).published
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = @blog.articles.create(article_params)
    if @article.save
      redirect_to blog_articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to blog_articles_path(@article.blog)
    else
      render :edit
    end
  end
  
  def show
  end

  def destroy
    @article.destroy
    redirect_to blog_articles_path(@article.blog)
  end
  
  private
  def find_blog
    @blog = Blog.find_by(id:params[:blog_id])
  end

  def find_article
    @article = Article.find_by(id:params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :publish)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_blog, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @blogs = Blog.all
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      UserBlog.create(user: current_user,
                      blog: @blog,
                      role: "owner")
      redirect_to blogs_path(@blog)
    else
      render :new
    end
  end
  
  def show
    @blog = Blog.find_by(id:params[:id])
    @articles = Article.where(blog_id: params[:blog_id]).published
    if params[:search]
    @search_result = User.where("email LIKE ?", "%#{params[:search]}%")
    else
      #
    end 
  end

  def edit
    authorize @blog
  end
  
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end
  
  def destroy
    @blog.delete
    redirect_to blogs_path, notice: 'blog deleted!'
  end

  # def search
  #   @user = User.where("email LIKE ?", "%#{params[:search]}%")
  # end
  
  private
  def check_blog_user
    current_user.blogs.where(id: blog.id).present?
  end

  def find_blog
    @blog = current_user.blogs.find_by(id:params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :author).merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationController
  before_action :authenticate_user!

  def after_sign_up_path_for(resource)
    blogs_path || super
  end

  def create
    sign_in(@user)
    redirect_to blogs_path
  end
end

app/controllers/user_blogs_controller.rb
class UserBlogsController < ApplicationController
  def change_role
    user_email = params[:email]
    @user = User.find_by(email: user_email)
    user_blog = @user.user_blogs.where(blog_id: params[:id])
    if user_blog.present?
      redirect_to blog_path(params[:id])
      flash.alert = "The user already owned this blog"
    else
      @user.blogs << Blog.find(params[:id]) 
      @user.user_blogs.last.update(role: 2)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  before_action :authenticate_user!

  def after_sign_up_path_for(resource)
    blogs_path || super
  end

  def create
    sign_in(@user)
    redirect_to blogs_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def can_edit?(num)
    current_user.blog_ids.include?(num)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def can_edit?(blog_id)
    current_user.blog_ids.include?(blog_id.to_i)
  end
end

app/helpers/user_blogs_helper.rb
module UserBlogsHelper
end

app/views/articles/edit.html.erb
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Edit article</h1>
</div>

<%= form_with model: @article do |f| %>
<div class="container mt-3">
  <div class="mb-3 mt-3">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control mt-3", placeholder:"Title of the article.." %>
  </div>
  <div class="mb-3">
    <%= f.label :content %>
    <%= f.text_area :content, class:"form-control mt-3", placeholder:"Once upon a time...." %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.collection_radio_buttons :publish, Article.publishes, :first, :first %>
  </div>
  <%= f.submit value='Edit', class:"btn btn-primary my-2"%>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>
<div class="container-fluid p-5 bg-info text-white text-center">
  <h1><%= @blog.title %></h1>
  <p>Feel free to read and take away thoughts</p>
  <%= link_to 'Back to blogs', blogs_path, class:'text-warning' %><br>
  <% if can_edit?(@blog.id) == true %>
  <%= link_to 'Write a new article', new_blog_article_path, class:'text-warning' %>
  <% end %>
</div>
  
<div class="container mt-5">
  <div class="row">
    <% @articles.each do |article| %>
    <div class="col-sm-4 bg-light my-2 card">
      <h3><%= article.title %></h3>
      <p><%= article.content %></p>
      <p><%= link_to 'Article details', article_path(article.id), class:'btn btn-outline-info' %></p>
      <% if can_edit?(@blog.id) == true %>
      <p><%= link_to 'Edit', edit_article_path(article), class:'text-info' %></p>
      <p><%= link_to 'Delete', article_path(article), class:'text-danger', method: 'delete', data: { confirm: 'Sure to delete article?' } %></p>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Add new article</h1>
  <p><%= link_to 'See all my articles', blog_articles_path(@blog), class:'text-warning' %></p>
</div>

<%= form_for ([:blog, @article]) do |f| %>
<div class="container mt-3">
  <div class="mb-3 mt-3">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control mt-3", placeholder:"Title of the article.." %>
  </div>
  <div class="mb-3">
    <%= f.label :content %>
    <%= f.text_area :content, class:"form-control mt-3", placeholder:"Once upon a time...." %>
  </div>
   <div class="field">
    <%= f.label :publish %><br />
    <%= f.collection_radio_buttons :publish, Article.publishes, :first, :first %>
  </div>
  <%= f.submit value='Post', class:"btn btn-primary my-2"%>
  <% end %>
</div>

app/views/articles/show.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1><%= @article.title %></h1>
  <p><%= link_to 'See all articles', blog_articles_path(@article.blog_id), class:'text-warning' %></p>
</div>
<div class="text-center container p-2 my-5 bg-lightgrey text-black">
  <p><%= @article.content %></p>
</div>

app/views/blogs/edit.html.erb
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Edit blog</h1>
</div>

<%= form_for(@blog) do |f| %>
<div class="container mt-3">
  <h2>Edit your blog details</h2>
    <div class="mb-3">
      <%= f.label :author %>
      <%= f.text_field :author, class:"form-control mt-3", placeholder:"I'm..." %>
    </div>
    <div class="mb-3 mt-3">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control mt-3", placeholder:"Myblog" %>
    </div>
    <div class="mb-3">
      <%= f.label :content %>
      <%= f.text_area :content, class:"form-control mt-3", placeholder:"It's all about Myblog...." %>
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
  <% end %>
</div>

app/views/blogs/index.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>
<div class="p-5 bg-primary text-white text-center">
  <h1>Myblog</h1>
  <p>To choose from below blogs and to see more</p>
</div>

<div class="container mt-5">
  <%= link_to 'Create new blog', new_blog_path, class:'btn btn-primary' %>
  <div class="row">
  <% @blogs.each do |blog| %>
    <div class="col-sm-4 bg-light my-2 card">
      <h3><%= blog.title %></h3>
      <p>By: <%= blog.author %></p>
      <p><%= blog.content %></p>
      <p><%= link_to 'Blog details', blog_path(blog.id), class:'btn btn-outline-info' %></p>
      <% if can_edit?(blog.id) == true %>
      <p><%= link_to 'Edit blog', edit_blog_path(blog), class:'text-info' %></p>
      <p><%= link_to 'Delete blog', blog_path(blog), class:'text-danger', method: 'delete', data: { confirm: 'Sure to delete blog?' } %></p>  
      <% end %> 
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>

<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Create a new blog</h1>
  <p><%= link_to 'Back to Myblog list', blogs_path, class:'text-warning' %></p>
</div>

<%= form_for(@blog) do |f| %>
<div class="container mt-3">
  <h2>Let us know what is the blog about</h2>
  <p>Enter your name, title and content</p>
    <div class="mb-3">
      <%= f.label :author %>
      <%= f.text_field :author, class:"form-control mt-3", placeholder:"I'm..." %>
    </div>
    <div class="mb-3 mt-3">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control mt-3", placeholder:"Myblog" %>
    </div>
    <div class="mb-3">
      <%= f.label :content %>
      <%= f.text_area :content, class:"form-control mt-3", placeholder:"It's all about Myblog...." %>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  <% end %>
</div>

app/views/blogs/show.html.erb
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"my-2 d-flex flex-row-reverse" %>
<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1><%= @blog.title %></h1>
  <p>By:<%= @blog.author %></p>
  <p><%= link_to 'Back to Myblog list', blogs_path, class:'text-warning' %></p>
  <p><%= link_to 'See all articles', blog_articles_path(@blog.id), class:'text-warning' %></p>
</div>
<div class="container">
<% if can_edit?(@blog.id) == true %>
  <p>Invite your friend to own this blog together</p>
  <%= form_tag blog_path, method: "get" do %>
  <%= text_field_tag :search, params[:search], placeholder: 'please enter e-mail', class: 'form-controller' %>
  <%= submit_tag "search", name: nil, class:'btn btn-info' %>
  <% end %>
  <%= render 'shared/search_result' %>
<% end %>
</div>
<div class="text-center container p-2 my-5 bg-lightgrey text-black">
  <p><%= @blog.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_search_result.html.erb
<% if @search_result %>
  <% @search_result.each do |user| %>
  <%= user.email %><span class="btn btn-outline-info"><%= link_to "Add user", user_blog_path(request.parameters.merge({email: "#{user.email}"})), method: :post %></span>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="container-fluid p-5 bg-info text-white text-center">
  <h1>Welcome to Myblog</h1>
  <p>Share your thoughts and ideas</p>
</div>
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= link_to 'Myblog', blogs_path %></h1>
        <p class="lead text-muted">You can create one or more blogs, and post out articles in each blog.</p>
        <p>
          <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-secondary" %>
          <%= link_to 'Sign in', new_user_session_path, class:"btn btn-primary my-2" %>
          <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class:"btn btn-outline-secondary my-2" %>
        </p>
      </div>
    </div>
  </section>
</main>